##Author: Andrew Techmeier
library(shiny)
shinyUI(fluidPage(
  titlePanel("Estimation of Male Body Fat Percentage"),
  p("This application uses the 'fat' dataset in the 'UsingR' package.  It fits a linear model to predict male body fat percentage based on age, BMI, neck, chest, abdomen, hip, thigh, knee, ankle, bicep, forearm, and wrist measurements."),
  p("Use the sliders below to change measurement values.  Results are displayed at the bottom of this application."),
  fluidRow(
      column(4,
        sliderInput("age", "Age (years):",
                    min=18,
                    max=100,
                     value = 25),
        sliderInput("weight",
                  "Weight (lbs):",
                  min = 50,
                  max = 400,
                  value = 150),
      sliderInput("height",
                   "Height (inches):",
                  min = 48,
                  max = 90,
                  value = 72
                  ),
      sliderInput("neck",
                   "Neck Circumference (cm):",
                  min = 25,
                  max = 55,
                  value = 38),
      sliderInput("chest",
                   "Chest Circumference (cm):",
                  min = 60,
                  max = 150,
                  value = 100)),
      column(4,
      sliderInput("abdomen",
                   "Abdomen Circumference (cm):",
                  min = 60,
                  max = 160,
                  value = 90),
      sliderInput("hip",
                   "Hip Circumference (cm):",
                  min = 60,
                  max = 160,
                  value = 100),
      sliderInput("thigh",
                   "Thigh Circumference (cm):",
                  min = 40,
                  max = 100,
                   value = 60),
      sliderInput("knee",
                   "Knee Circumference (cm):",
                  min = 20,
                  max = 60,
                  value = 40)),
      column(4,
      sliderInput("ankle",
                   "Ankle Circumference (cm):",
                  min = 15,
                  max = 45,
                  value = 25),
      sliderInput("bicep",
                   "Extended bicep Circumference (cm):",
                  min = 20,
                  max = 60,
                  value = 30),
      sliderInput("forearm",
                   "Forearm Circumference (cm):",
                  min = 15,
                  max = 45,
                  value = 29),
      sliderInput("wrist",
                   "Wrist Circumference (cm):",
                  min = 10,
                  max = 25,
                  value = 18))
    ),
      h2(textOutput("text"))
  )
)
